version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoSettings__ConnectionString=mongodb://mongo:27017
      - MongoSettings__Database=DeveloperStore

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"